package org.group3.tutorlink.entity;

import jakarta.persistence.*;
import lombok.*;

import java.time.LocalDate;
import java.util.UUID;

@Entity
@Table(name = "revenue_reports")
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class RevenueReport extends BaseEntity{

    @Id
    private UUID id;

    private LocalDate periodStart;

    private LocalDate periodEnd;

    private double totalRevenue;

    private int totalTransactions;

    // RevenueReport n -- 1 Admin (generated by), optional
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "generated_by_admin_id")
    private Admin generatedByAdmin;
}
